# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: godev

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: godev
    main: .
    binary: godev
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jmoyonero/godev/cmd.Version=v{{ .Version }}
      - -X github.com/jmoyonero/godev/cmd.Commit={{ .ShortCommit }}
      - -X github.com/jmoyonero/godev/cmd.Date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: godev
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: jmoyonero
    name: godev
  prerelease: auto
