package docker

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// GenerateUniversalDockerfile produces a standardized, hardened multi-stage Dockerfile
// for any Go microservice by scanning the cmd/ directory for entrypoints.
func GenerateUniversalDockerfile() (string, error) {
	goVersion := detectGoVersion()
	targets := detectCmdTargets()

	var sb strings.Builder
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString("# Standard Universal Go Dockerfile - Generated by godev\n")
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString(fmt.Sprintf("FROM golang:%s-alpine AS builder\n\n", goVersion))
	sb.WriteString("ARG SSH_DEPLOY_KEY_B64=\"\"\n")
	sb.WriteString("ENV GOPRIVATE=github.com/jmoyonero/*\n")
	sb.WriteString("WORKDIR /app\n\n")
	sb.WriteString("RUN apk add --no-cache git openssh-client\n\n")
	sb.WriteString("COPY go.mod go.sum ./\n")
	sb.WriteString("RUN mkdir -p \"$HOME/.ssh\" && \\\n")
	sb.WriteString("    if [ -n \"$SSH_DEPLOY_KEY_B64\" ]; then \\\n")
	sb.WriteString("      printf '%s' \"$SSH_DEPLOY_KEY_B64\" | base64 -d > \"$HOME/.ssh/id_ed25519\" && \\\n")
	sb.WriteString("      chmod 600 \"$HOME/.ssh/id_ed25519\" && \\\n")
	sb.WriteString("      ssh-keyscan github.com >> \"$HOME/.ssh/known_hosts\" 2>/dev/null && \\\n")
	sb.WriteString("      git config --global url.\"git@github.com:jmoyonero/\".insteadOf \"https://github.com/jmoyonero/\"; \\\n")
	sb.WriteString("    fi && \\\n")
	sb.WriteString("    go mod download && \\\n")
	sb.WriteString("    rm -rf \"$HOME/.ssh\" && \\\n")
	sb.WriteString("    git config --global --unset-all url.\"git@github.com:jmoyonero/\".insteadOf 2>/dev/null || true\n\n")
	sb.WriteString("COPY . .\n\n")
	sb.WriteString("RUN go generate ./... 2>/dev/null || true\n\n")
	sb.WriteString("RUN mkdir -p /app/bin && \\\n")
	sb.WriteString("    for dir in cmd/*/; do \\\n")
	sb.WriteString("      if [ -d \"$dir\" ]; then \\\n")
	sb.WriteString("        bin=$(basename \"$dir\"); \\\n")
	sb.WriteString("        echo \"Building $bin from $dir...\"; \\\n")
	sb.WriteString("        CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags=\"-s -w\" -o /app/bin/$bin ./cmd/$bin; \\\n")
	sb.WriteString("      fi; \\\n")
	sb.WriteString("    done\n\n")
	sb.WriteString("# Runtime base stage (hardened non-root)\n")
	sb.WriteString("FROM alpine:3.21 AS runtime-base\n")
	sb.WriteString("RUN apk add --no-cache tzdata ca-certificates && \\\n")
	sb.WriteString("    addgroup -g 10001 appgroup && \\\n")
	sb.WriteString("    adduser -u 10001 -G appgroup -D -s /bin/false appuser\n")
	sb.WriteString("WORKDIR /app\n\n")

	// Generate target stages for each detected flavor
	for _, target := range targets {
		sb.WriteString(fmt.Sprintf("# Target: %s\n", target))
		sb.WriteString(fmt.Sprintf("FROM runtime-base AS %s\n", target))
		sb.WriteString(fmt.Sprintf("COPY --from=builder --chown=10001:10001 /app/bin/%s /app/bin/%s\n", target, target))
		sb.WriteString(fmt.Sprintf("RUN ln -s /app/bin/%s /app/%s\n", target, target))
		sb.WriteString("USER 10001:10001\n")
		sb.WriteString("EXPOSE 8080\n")
		sb.WriteString(fmt.Sprintf("CMD [\"/app/bin/%s\"]\n\n", target))
	}

	// Also generate generic target app
	sb.WriteString("# Target: app (generic parameterized by TARGET build arg)\n")
	sb.WriteString("FROM runtime-base AS app\n")
	sb.WriteString("ARG TARGET=api\n")
	sb.WriteString("COPY --from=builder --chown=10001:10001 /app/bin/${TARGET} /app/entrypoint\n")
	sb.WriteString("USER 10001:10001\n")
	sb.WriteString("EXPOSE 8080\n")
	sb.WriteString("CMD [\"/app/entrypoint\"]\n")

	return sb.String(), nil
}

func detectGoVersion() string {
	f, err := os.Open("go.mod")
	if err != nil {
		return "1.26.6"
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "go ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return parts[1]
			}
		}
	}
	return "1.26.6"
}

func detectCmdTargets() []string {
	entries, err := os.ReadDir("cmd")
	if err != nil {
		return []string{"api"}
	}

	var targets []string
	for _, e := range entries {
		if e.IsDir() {
			targets = append(targets, e.Name())
		}
	}
	if len(targets) == 0 {
		return []string{"api"}
	}
	return targets
}
