package docker

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// fallbackGoVersion builds the image when go.mod declares no version.
const fallbackGoVersion = "1.27.1"

// SSHSecretID is the BuildKit secret holding the private key used to download
// private modules. It is mounted for the download layer only, so it never
// reaches an image or the build metadata, unlike a --build-arg.
const SSHSecretID = "godev_ssh_key" //nolint:gosec // G101: the id of the secret, not a credential

// Options controls how the universal Dockerfile is generated.
type Options struct {
	// PrivateModulePrefix is the "host/owner" prefix of the private Go modules
	// the project depends on, such as "github.com/acme". The builder stage
	// exports it through GOPRIVATE and fetches those modules over SSH with the
	// key mounted as the SSHSecretID build secret. When it is empty, the build
	// only uses public modules and no key is needed.
	PrivateModulePrefix string
}

// GenerateUniversalDockerfile produces a standardized, hardened multi-stage Dockerfile
// for any Go microservice by scanning the cmd/ directory for entrypoints.
func GenerateUniversalDockerfile(opts Options) string {
	goVersion := detectGoVersion()
	targets := detectCmdTargets()

	var sb strings.Builder
	if opts.PrivateModulePrefix != "" {
		// Required by the RUN --mount=type=secret of the dependency layer, and
		// it must come before anything else.
		sb.WriteString("# syntax=docker/dockerfile:1\n")
	}
	sb.WriteString("# ==============================================================================\n")
	sb.WriteString("# Standard Universal Go Dockerfile - Generated by godev\n")
	sb.WriteString("# ==============================================================================\n")
	fmt.Fprintf(&sb, "FROM golang:%s-alpine AS builder\n\n", goVersion)

	writeDependencyStage(&sb, opts.PrivateModulePrefix)

	sb.WriteString("COPY . .\n\n")
	sb.WriteString("RUN go generate ./... 2>/dev/null || true\n\n")
	sb.WriteString("RUN mkdir -p /app/bin && \\\n")
	sb.WriteString("    for dir in cmd/*/; do \\\n")
	sb.WriteString("      if [ -d \"$dir\" ]; then \\\n")
	sb.WriteString("        bin=$(basename \"$dir\"); \\\n")
	sb.WriteString("        echo \"Building $bin from $dir...\"; \\\n")
	sb.WriteString("        CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags=\"-s -w\" -o /app/bin/$bin ./cmd/$bin; \\\n")
	sb.WriteString("      fi; \\\n")
	sb.WriteString("    done\n\n")
	sb.WriteString("# Runtime base stage (distroless non-root, 0 CVEs, no shell)\n")
	sb.WriteString("FROM gcr.io/distroless/static-debian12:nonroot AS runtime-base\n")
	sb.WriteString("WORKDIR /app\n\n")

	// Generate target stages for each detected flavor
	for _, target := range targets {
		fmt.Fprintf(&sb, "# Target: %s\n", target)
		fmt.Fprintf(&sb, "FROM runtime-base AS %s\n", target)
		fmt.Fprintf(&sb, "COPY --from=builder --chown=nonroot:nonroot /app/bin/%s /app/bin/%s\n", target, target)
		fmt.Fprintf(&sb, "COPY --from=builder --chown=nonroot:nonroot /app/bin/%s /app/%s\n", target, target)
		sb.WriteString("USER nonroot:nonroot\n")
		sb.WriteString("EXPOSE 8080\n")
		fmt.Fprintf(&sb, "CMD [\"/app/bin/%s\"]\n\n", target)
	}

	// Also generate generic target app
	sb.WriteString("# Target: app (generic parameterized by TARGET build arg)\n")
	sb.WriteString("FROM runtime-base AS app\n")
	sb.WriteString("ARG TARGET=api\n")
	sb.WriteString("COPY --from=builder --chown=nonroot:nonroot /app/bin/${TARGET} /app/entrypoint\n")
	sb.WriteString("USER nonroot:nonroot\n")
	sb.WriteString("EXPOSE 8080\n")
	sb.WriteString("CMD [\"/app/entrypoint\"]\n")

	return sb.String()
}

// writeDependencyStage writes the dependency download layer. With a private
// module prefix it also configures GOPRIVATE and, when a deploy key is mounted,
// an SSH rewrite for that prefix; the key lives in a tmpfs for that single RUN
// and the credentials it leaves behind are removed in the same layer.
func writeDependencyStage(sb *strings.Builder, privatePrefix string) {
	if privatePrefix == "" {
		sb.WriteString("WORKDIR /app\n\n")
		sb.WriteString("RUN apk add --no-cache git\n\n")
		sb.WriteString("COPY go.mod go.sum ./\n")
		sb.WriteString("RUN go mod download\n\n")
		return
	}

	host, _, _ := strings.Cut(privatePrefix, "/")
	sshURL := strings.Replace(privatePrefix, "/", ":", 1)

	fmt.Fprintf(sb, "ENV GOPRIVATE=%s/*\n", privatePrefix)
	sb.WriteString("WORKDIR /app\n\n")
	sb.WriteString("RUN apk add --no-cache git openssh-client\n\n")
	sb.WriteString("COPY go.mod go.sum ./\n")
	fmt.Fprintf(sb, "# The deploy key is mounted for this layer only: pass it with\n")
	fmt.Fprintf(sb, "# docker build --secret id=%s,src=<key>, as godev does.\n", SSHSecretID)
	fmt.Fprintf(sb, "RUN --mount=type=secret,id=%s \\\n", SSHSecretID)
	fmt.Fprintf(sb, "    if [ -s /run/secrets/%s ]; then \\\n", SSHSecretID)
	sb.WriteString("      mkdir -p \"$HOME/.ssh\" && \\\n")
	fmt.Fprintf(sb, "      cp /run/secrets/%s \"$HOME/.ssh/id_ed25519\" && \\\n", SSHSecretID)
	sb.WriteString("      chmod 600 \"$HOME/.ssh/id_ed25519\" && \\\n")
	fmt.Fprintf(sb, "      ssh-keyscan %s >> \"$HOME/.ssh/known_hosts\" 2>/dev/null && \\\n", host)
	fmt.Fprintf(sb, "      git config --global url.\"git@%s/\".insteadOf \"https://%s/\"; \\\n", sshURL, privatePrefix)
	sb.WriteString("    fi && \\\n")
	sb.WriteString("    go mod download; \\\n")
	sb.WriteString("    STATUS=$?; \\\n")
	sb.WriteString("    rm -rf \"$HOME/.ssh\"; \\\n")
	fmt.Fprintf(sb, "    git config --global --unset-all url.\"git@%s/\".insteadOf 2>/dev/null || true; \\\n", sshURL)
	sb.WriteString("    exit $STATUS\n\n")
}

// DetectPrivateModulePrefix returns the "host/owner" prefix of the module
// declared in go.mod, which is where a project's own private modules live. It
// returns an empty string when go.mod is missing or its module path is not a
// repository path, as in "module myapp".
func DetectPrivateModulePrefix() string {
	parts := strings.Split(goModDirective("module"), "/")
	if len(parts) < 3 || !strings.Contains(parts[0], ".") {
		return ""
	}
	return parts[0] + "/" + parts[1]
}

// goModDirective returns the value of the first "<name> <value>" line in
// go.mod, or an empty string when go.mod or the directive is missing.
func goModDirective(name string) string {
	f, err := os.Open("go.mod")
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		parts := strings.Fields(scanner.Text())
		if len(parts) >= 2 && parts[0] == name {
			return parts[1]
		}
	}
	return ""
}

func detectGoVersion() string {
	if version := goModDirective("go"); version != "" {
		return version
	}
	return fallbackGoVersion
}

func detectCmdTargets() []string {
	entries, err := os.ReadDir("cmd")
	if err != nil {
		return []string{"api"}
	}

	var targets []string
	for _, e := range entries {
		if e.IsDir() {
			targets = append(targets, e.Name())
		}
	}
	if len(targets) == 0 {
		return []string{"api"}
	}
	return targets
}
